# Generated by Django 5.2.8 on 2025-11-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.FloatField()),
                ('description', models.TextField()),
                ('is_top_five', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'Movie'), (2, 'Series'), (3, 'Cartoon'), (4, 'Anime')], default=1)),
                ('ganre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main.ganre')),
            ],
        ),
    ]
