# Generated by Django 5.2.8 on 2025-11-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ganre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ganre',
            new_name='genre',
        ),
    ]
