# Generated by Django 5.2.8 on 2025-11-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ganre_genre_rename_ganre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ganre/'),
        ),
    ]
