# Generated by Django 5.2.8 on 2025-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='created_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
