# Generated by Django 5.2.8 on 2025-12-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_sitereview_created_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанри"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Фільм", "verbose_name_plural": "Фільми"},
        ),
        migrations.AlterModelOptions(
            name="sitereview",
            options={"verbose_name": "Відгук", "verbose_name_plural": "Відгуки"},
        ),
        migrations.AlterField(
            model_name="genre",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ganre/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.FloatField(verbose_name="Тривалість"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="main.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_top_five",
            field=models.BooleanField(default=False, verbose_name="Топ 5"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(verbose_name="Дата випуску"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tag",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Тег"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Movie"), (2, "Series"), (3, "Cartoon"), (4, "Anime")],
                default=1,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="sitereview",
            name="created_time",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, verbose_name="Час створення"
            ),
        ),
        migrations.AlterField(
            model_name="sitereview",
            name="mark",
            field=models.IntegerField(verbose_name="Оцінка"),
        ),
        migrations.AlterField(
            model_name="sitereview",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Ім'я користувача"),
        ),
        migrations.AlterField(
            model_name="sitereview",
            name="text",
            field=models.TextField(verbose_name="Текст відгуку"),
        ),
    ]
